---
title: "Projects and Tutorials"
---

##Tutorials  
- [2018 MERL Tech DC workshop: Up your Data Game with R](merl.tech.html)
This workshop will introduce participants to the possibilities of using the free and open-source R programming language and software environment for data processing, analysis, and visualization. For many, Microsoft Excel is the tool of choice when working with data. By simply clicking, pointing, and dragging things with your mouse, you can accomplish many data-related tasks. What R offers is the ability to do the same tasks and much more in a fraction of the time it would in Excel, with larger data sets, fewer errors, and more transparency. Participants will see satisfying examples of using R to do common data tasks and, working back from those examples, learn key R programming skills in the process. The workshop facilitator will use a fun and freely-accessible dataset and examples from popular R “packages” to perform common data tasks, including cleaning, exploring, and plotting data. Participants will see right away what data science can do for them and the many advantages of using R.


##Projects
This page is under construction. I'll be adding fun data projects here.

